### ISSUE TITLE
Can we delete this GitHub repository?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cite1-utils#1]
This repo does not appear to be in use anymore.

We will delete the repository on 2022-05-05 unless if there is an objection from the CITE or TEAM Engine community.

**Comment by ghobona** [comment]
Cc: @dstenger

**Comment by dstenger** [comment]
Those three projects still use this library as dependency:
* https://github.com/opengeospatial/ets-wms11/blob/master/pom.xml
* https://github.com/opengeospatial/ets-wfs10/blob/master/pom.xml
* https://github.com/opengeospatial/ets-wcs10/blob/master/pom.xml

```
    <dependency>
      <groupId>org.opengis.cite</groupId>
      <artifactId>cite1-utils</artifactId>
      <version>1.1.1</version>
    </dependency>
```

**Comment by ghobona** [comment]
Ok, thanks.

We will keep the ETS.
